name: DiffBlue Cover Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install DiffBlue Cover
      run: |
        wget https://download.diffblue.com/cover-x.y.z-linux.tar.gz
        tar -xzf cover-x.y.z-linux.tar.gz
        ./cover-x.y.z-linux/bin/cover install

    - name: Run DiffBlue Cover
      run: |
        ./cover-x.y.z-linux/bin/cover run

    - name: Commit and push generated tests
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add generated tests by DiffBlue Cover"
        git push
