name: Print Message on Push

on:
  push:
    branches:
      - main  # 你可以根据需要指定分支，这里是示例为主分支

jobs:
  build:
    runs-on: ubuntu-latest  # 指定运行环境

    steps:
    - name: Print a message
      run: echo "Hello, World! This is a message printed by GitHub Actions on push."
